// // Generated by dts-bundle v0.7.3

declare module 'destiny-ui-x' {
    import { make } from "destiny-ui-x/functional/index";
    import { makeFrom } from "destiny-ui-x/functional/index";
    import { xml } from "destiny-ui-x/functional/index";
    import { xml as css } from "destiny-ui-x/functional/index";
    import { xml as html } from "destiny-ui-x/functional/index";
    export { make, makeFrom, xml, css, html };
}

declare module 'destiny-ui-x/functional/index' {
    export function make(fn: () => typeof FnBaseComponent, optional_name?: string): {
        new (): {
            [x: string]: any;
            activated(props: any): void;
            unactivated: boolean;
            connectedCallback(...args: any[]): void;
            disconnectedCallback(): void;
        };
        name: string;
    };
    export function makeFrom(U: any, fn: () => typeof FnBaseComponent, optional_name?: string): {
        new (): {
            [x: string]: any;
            activated(props: any): void;
            unactivated: boolean;
            connectedCallback(...args: any[]): void;
            disconnectedCallback(): void;
        };
        name: string;
    };
    export function xml(strings?: string[], ...props: any[]): any;
    export function upgrade(df?: HTMLTemplateElement): Element | null;
    import { FnBaseComponent } from "destiny-ui-x/functional/base-component";
}

declare module 'destiny-ui-x/functional/base-component' {
    export function FnExtender(U: any): {
        new (): {
            [x: string]: any;
            unactivated: boolean;
            connectedCallback(...args: any[]): void;
            disconnectedCallback(): void;
            activated(): void;
        };
        [x: string]: any;
    };
    const FnBaseComponent_base: {
        new (): {
            [x: string]: any;
            unactivated: boolean;
            connectedCallback(...args: any[]): void;
            disconnectedCallback(): void;
            activated(): void;
        };
        [x: string]: any;
    };
    export class FnBaseComponent extends FnBaseComponent_base {
    }
    export {};
}

